config/routes.rb
Rails.application.routes.draw do
  
  root "articles#index"
  resources :articles
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get '/register', to: 'users#register'
  get '/login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'profile', to: 'users#show', as: 'profile'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user, :optional => true, foreign_key: "author_id"
    has_many :votes, foreign_key: "article_id"
    has_many :categories, foreign_key: "article_id"

    validates :title, :text, presence: true
    validates :description, length: { minimum: 25}
    validates :image_file
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :article, foreign_key: "article_id"
end

app/models/user.rb
class User < ApplicationRecord
 
    has_many :votes, foreign_key: "user_id"
    has_many :articles, foreign_key: "author_id"
    

    validates :email, :name, uniqueness: true, presence: true
    has_one_attached :avatar
end

app/models/vote.rb
class Vote < ApplicationRecord
    belongs_to :user, foreign_key: "user_id"
    belongs_to :article, foreign_key: "article_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
helper_method :current_user

def authorize
  redirect_to login_url, alert: "Not authorized" if current_user.nil?
end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    article_params =
    params.require(:article).
    permit(:title, :text)
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @article = Article.find(params[:id])
    article_params =
    params.require(:article).
    permit(:title, :text)
    @article.update(article_params)
    redirect_to articles_path(@articles)
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    article_params =
    params.require(:article).
    permit(:title, :text, :image_file)
    @event.destroy
    redirect_to articles_path
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    @latest_article = Article.last
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.fetch(:category, {})
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by_name(params[:name])
    if session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Wrong username"
      render "register"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.new
  end

  def register
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
  
    if @user.save
      redirect_to login_path, notice: 'Welcome! Now you can login by typing your name'
    else
      render :register
    end
  end

  private

def user_params
  params.require(:user).permit( :name, :email, :avatar)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def self.find_user_by(value)
        where(["name = :value OR email = :value", {value: value}]).first
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_footer.html.erb
<%# <footer>
        <div class="footer-container">
            <ul class="d-flex list-unstyled">
                <li>
                    <a href="https://twitter.com/mece_ka">
                        <i class="fab fa-twitter fa-2x"></i>
                    </a>
                </li>
                <li>
                    <a href="https://www.linkedin.com/in/meceka/">
                        <i class="fab fa-linkedin-in fa-2x"></i>
                    </a>
                </li>
                <li>
                    <a href="https://github.com/mcihadkurel">
                        <i class="fab fa-github fa-2x"></i>
                    </a>
                </li>
            </ul>
            <div class="d-flex align-items-center flex-column flex-md-row">
                <p class="mr-md-5">Made With <span>&hearts;</span> BY <a href="https://github.com/mcihadkurel">Muhammed Kurel</a></p>
                <p class="ml-md-5">Copyright &copy; 2020</p>
            </div>
        </div>
    </footer> %>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/_header.html.erb

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="navbar-brand candy">
  <%= link_to "CANDYMANDY", root_path %>
  </div>
  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-left">
      <li class="nav-item active">
        <%= link_to "CREATE ARTİCLE", new_article_path %>
      </li>     
    </ul>    
  </div>
  <div class="navbar-right mr-3">
  <div class="login">
  <% if current_user %>
  Hi <%= current_user.name %>
  <%= link_to "LOGOUT", logout_path %>
  |
  <%= link_to "PROFİLE", profile_path %>
  <% else %>
  <%= link_to "LOGİN", login_path %>
  |
  <%= link_to "SİGNUP", register_path %>
  <% end %>
  </div>
  </div>
</nav>

app/views/articles/edit.html.erb
<h1>Editing Article <%= @article.title %></h1>

<%= form_with(model: @article, local: true) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :description %>
    <%= f.text_area :text %>

    <%= f.submit %>
<% end %>

app/views/articles/index.html.erb
<%= render 'header' %>

<ul>
<% @articles.each do |article| %>
<li>
<strong><%= article.title %></strong>
<div class="image">
<%= image_tag(article.image_file) %>
</div>
<%= article.text %>
<%= article.author_id %>
</li>
<% end %>
</ul>
<%= link_to "Edit", edit_article_path(:id), class: "button" %>
<%= link_to "Delete", @article, class: "button", method: :delete %>
<br>
<%= link_to "Add New Article", new_article_path, class: "button" %>
<%= render 'footer' %>




app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_with(model: @article, local: true) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :description %>
    <%= f.text_area :text %>

    <%= f.label :image_file %>
    <%= f.text_field :image_file %>

    <%= f.submit %>
<% end %>


<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="image">
<%= image_tag(article.image_file) %>
</div>

<%= link_to 'Edit', edit_article_path(@article) %> |    
<%= link_to 'Back', articles_path %>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <%= @latest_article.title %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Candymandy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  
    <%= yield %>
  </body>
</html>

app/views/users/register.html.erb
<div class="container">
<h1>Sign Up</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="gravatar_edit">
    <%= f.label :Profilepic %><br />
      <%= f.file_field :avatar, class: "form-control",
        placeholder: 'Upload picture',
        id: "change-img-field",
        direct_upload: true
        %>
    </div>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "username", class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autocomplete: "email", class: "form-control" %>
  </div>

  <div class="actions text-center mt-5">
    <%= f.submit "Sign up", class: "btn btn-lg btn-info" %>
  </div>
<% end %>
</div>

app/views/users/show.html.erb
<div class="container">

<h1>Hi; <br><%= current_user.name %></h1>
<div class="col-6">
<%= image_tag(current_user.avatar, alt: "avatar", class: "avatar rounded-circle", id: "avatar") %>
</div>

</div>
</div>